- name: Load environment variables
  include_vars:
    file: "{{ playbook_dir }}/../.env.yml"
    name: env_vars

- name: Run backend container
  docker_container:
    name: simple-api
    image: hadjabah/tp-devops-backend:latest
    networks:
      - name: app_network
    ports:
      - "{{ env_vars.APP_PORT }}:8080"
    env:
      SPRING_DATASOURCE_URL: "{{ env_vars.SPRING_DATASOURCE_URL }}"
      SPRING_DATASOURCE_USERNAME: "{{ env_vars.SPRING_DATASOURCE_USERNAME }}"
      SPRING_DATASOURCE_PASSWORD: "{{ env_vars.SPRING_DATASOURCE_PASSWORD }}"





