name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify
      
      - name: Sonar Cloud integration
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=HadjaAissatouBah_tp-devops-correction-docker -Dsonar.organization=hadjaaissatou -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml


  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./devops-front-main
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Set up SSH key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H hadja-aissatou.bah.takima.cloud >> ~/.ssh/known_hosts

      - name: Créer le fichier .env.yml depuis les secrets
        run: |
          cat <<EOF > .env.yml
          SPRING_DATASOURCE_URL: "${{ secrets.SPRING_DATASOURCE_URL }}"
          SPRING_DATASOURCE_USERNAME: "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
          SPRING_DATASOURCE_PASSWORD: "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
          POSTGRES_USER: "${{ secrets.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
          POSTGRES_DB: "${{ secrets.POSTGRES_DB }}"
          APP_PORT: "${{ secrets.APP_PORT }}"
          PROXY_PORT: "${{ secrets.PROXY_PORT }}"
          EOF

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
